@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div>
            <div class="panel panel-default">
                <div class="panel-heading"><h1>Privacy Policy</h1></div>

                <div class="panel-body">
                    <p>We at SocialAd know you care about how your personal information is used and shared, and we take your privacy seriously.  Please read the following to learn more about our Privacy Policy.<br />
<strong>By using or accessing the Services in any manner, you acknowledge that you accept the practices and policies outlined in this Privacy Policy, and you hereby consent that we will collect, use, and share your information in the following ways. </strong></p>
<p>Remember that your use of SocialAd's Services is at all times subject to the Terms of Use (<a href="{{ url()->current() }}">{{ url()->current() }}</a>), which incorporates this Privacy Policy.  Any terms we use in this Policy without defining them have the definitions given to them in the Terms of Use (<a href="{{ url()->current() }}">{{ url()->current() }}</a>).</p>
<h3>What does this Privacy Policy cover?</h3>
<p>This Privacy Policy covers our treatment of personally identifiable information (&#8220;Personal Information&#8221;) that we gather when you are accessing or using our Services, but not to the practices of companies we don’t own or control, or people that we don’t manage.  We gather various types of Personal Information from our users, as explained in more detail below, and we use this Personal Information internally in connection with our Services, including to personalize, provide, and improve our services, to allow you to set up a user account and profile, to contact you and allow other users to contact you, to fulfill your requests for certain products and services, and to analyze how you use the Services. In certain cases, we may also share some Personal Information with third parties, but only as described below.</p>
<p>As noted in the Terms of Use (<a href="{{ url()->current() }}">{{ url()->current() }}</a>), we do not knowingly collect or solicit personal information from anyone under the age of 13. If you are under 13, please do not attempt to register for the Services or send any personal information about yourself to us. If we learn that we have collected personal information from a child under age 13, we will delete that information as quickly as possible. If you believe that a child under 13 may have provided us personal information, please contact us at <a href="mailto:privacy@socialad.hidupmantap.com">privacy@socialad.hidupmantap.com</a></p>
<h3>Will SocialAd ever change this Privacy Policy?</h3>
<p>We’re constantly trying to improve our Services, so we may need to change this Privacy Policy from time to time as well, but we will alert you to changes by placing a notice on adespresso.com, by sending you an email, and/or by some other means. Please note that if you’ve opted not to receive legal notice emails from us (or you haven’t provided us with your email address), those legal notices will still govern your use of the Services, and you are still responsible for reading and understanding them.  If you use the Services after any changes to the Privacy Policy have been posted, that means you agree to all of the changes.  Use of information we collect now is subject to the Privacy Policy in effect at the time such information is collected.</p>
<h3>What Information does SocialAd Collect?</h3>
<h4>Information You Provide to Us:</h4>
<p>We receive and store any information you knowingly provide to us.  For example, through the registration process and/or through your account settings, we may collect Personal Information such as your name, email address, phone number, and third-party account credentials (for example, your Facebook account Id or other third party sites). If you provide your third-party account credentials to us or otherwise sign in to the Services through a third party site or service, you understand some content and/or information in those accounts (“Third Party Account Information”) may be transmitted into your account with us if you authorize such transmissions, and that Third Party Account Information transmitted to our Services is covered by this Privacy Policy; for example, your previous Facebook ads campaigns content. Certain information may be required to register with us or to take advantage of some of our features.</p>
<p>We may communicate with you if you’ve provided us the means to do so. For example, if you’ve given us your email address, we may send you promotional email offers on behalf of other businesses, or email you about your use of the Services. Also, we may receive a confirmation when you open an email from us. This confirmation helps us make our communications with you more interesting and improve our services. If you do not want to receive communications from us, please indicate your preference by writing to <a href="mailto:privacy@socialad.hidupmantap.com">privacy@socialad.hidupmantap.com</a> or using the unsubscribe link in each email.</p>
<h4>Information Collected Automatically</h4>
<p>Whenever you interact with our Services, we automatically receive and record information on our server logs from your browser or device, which may include your IP address, device identification, “cookie” information, the type of browser and/or device you’re using to access our Services, and the page or feature you requested. “Cookies” are identifiers we transfer to your browser or device that allow us to recognize your browser or device and tell us how and when pages and features in our Services are visited and by how many people.  You may be able to change the preferences on your browser or device to prevent or limit your device’s acceptance of cookies, but this may prevent you from taking advantage of some of our features. Our advertising partners may also transmit cookies to your browser or device, when you click on ads that appear on the Services. Also, if you click on a link to a third party website or service, such third party may also transmit cookies to you.  Again, this Privacy Policy does not cover the use of cookies by any third parties, and we aren’t responsible for their privacy policies and practices.</p>
<p>We may use this data to customize content for you that we think you might like, based on your usage patterns.  We may also use it to improve the Services – for example, this data can tell us how often users use a particular feature of the Services, and we can use that knowledge to make the Services interesting to as many users as possible.</p>
<h4>Online Tracking</h4>
<p>Through cookies we place on your browser or device, we may collect information about your online activity after you leave our Services.  Just like any other usage information we collect, this information allows us to improve the Services and customize your online experience, and otherwise as described in this Privacy Policy.  Your browser may offer you a “Do Not Track” option, which allows you to signal to operators of websites and online services (including third-party behavioral advertising services) that you do not wish such operators to track certain of your online activities over time and across different websites.  Our Services do not support Do Not Track requests at this time, which means that we may collect information about your online activity both while you are using the Services and after you leave our Services.</p>
<h3>Will SocialAd Share Any of the Personal Information it Receives?</h3>
<p>We neither rent nor sell your Personal Information in personally identifiable form to anyone. However, we may share your Personal Information with third parties as described in this section:</p>
<p><strong>Information that’s no longer personally identifiable. </strong> We may anonymize your Personal Information so that you are not individually identified, and provide that information to our partners. We may also provide aggregate usage information to our partners, who may use such information to understand how often and in what ways people use our Services, so that they, too, can provide you with an optimal online experience. However, we never disclose aggregate usage information to a partner in a manner that would identify you personally, as an individual.</p>
<p>We use Google Analytics to help analyze how Users use the Service. Google Analytics uses cookies to collect information such as how often Users visit the Service, what pages they visit, and what other sites they used prior to coming to the Service. We use the information we get from Google Analytics only to improve our Service. Google Analytics collects the IP address assigned to you on the date you visit the Service, but not your name or other personally identifying information. We do not combine the information generated through the use of Google Analytics with your Personal Information. Although Google Analytics plants a persistent Cookie on your web browser to identify you as a unique User the next time you visit the Service, the Cookie cannot be used by anyone but Google. Google’s ability to use and share information collected by Google Analytics about your visits to the Service is restricted by the Google Analytics Terms of Use and the Google Privacy Policy.</p>
<p><strong>Advertisers:</strong> We allow advertisers and/or merchant partners (“Advertisers”) to choose the demographic information of users who will see their advertisements and/or promotional offers and you agree that we may provide any of the information we have collected from you in non-personally identifiable form to an Advertiser, in order for that Advertiser to select the appropriate audience for those advertisements and/or offers. For example, we might use the fact you are located in San Francisco to show you ads or offers for San Francisco businesses, but we will not tell such businesses who you are.  Or, we might allow Advertisers to display their ads to users with similar usage patterns to yours, but we will not disclose usage information to Advertisers except in aggregate form, and not in a manner that would identify you personally.  Note that if an advertiser asks us to show an ad to a certain audience or audience segment and you respond to that ad, the advertiser may conclude that you fit the description of the audience they were trying to reach.</p>
<p><strong>User Profiles and Submissions:</strong> Certain user profile information, including your name, location, and any video or image content that such user has uploaded to the Services, may be displayed to other users to facilitate user interaction within the Services or address your request for our services.  Your account privacy settings may allow you to limit the other users who can see the Personal Information in your user profile and/or what information in your user profile is visible to others.  Please remember that any content you upload to your public user profile, along with any Personal Information or content that you voluntarily disclose online in a manner other users can view (on discussion boards, in messages and chat areas, etc.) becomes publicly available, and can be collected and used by anyone.  Your user name may also be displayed to other users if and when you send messages or comments or upload images or videos through the Services and other users can contact you through messages and comments.</p>
<p><strong>Protection of SocialAd and Others:</strong> We reserve the right to access, read, preserve, and disclose any information that we reasonably believe is necessary to comply with law or court order; enforce or apply our Terms of Use <a href="{{ url()->current() }}">{{ url()->current() }}</a>  and other agreements; or protect the rights, property, or safety of AdEspresso, our employees, our users, or others.</p>
<h3>Is Personal Information about me secure?</h3>
<p>Your account is protected by a password for your privacy and security.  If you access your account via a third party site or service, you may have additional or different sign-on protections via that third party site or service.  You must prevent unauthorized access to your account and Personal Information by selecting and protecting your password and limiting access to your computer or device and browser by signing off after you have finished accessing your account.</p>
<p>We endeavor to protect the privacy of your account and other Personal Information we hold in our records, but unfortunately, we cannot guarantee complete security.  Unauthorized entry or use, hardware or software failure, and other factors, may compromise the security of user information at any time.</p>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection


