@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div>
            <div class="panel panel-default">
                <div class="panel-heading"><h1>Terms and Conditions</h1></div>

                <div class="panel-body">

<p>These General Terms, the Acceptable Use Rules, the Payment Terms, (collectively, the “<strong>SocialAD Terms</strong>”) govern access to and use of any websites, products or services (collectively &#8220;<strong>Services</strong>&#8220;) offered by SocialAD Inc. (“<strong>SocialAD</strong>” or &#8220;<strong>we</strong>&#8220;).</p>
<p>OUR SERVICES ARE NOT FOR CONSUMERS OR PRIVATE OR HOUSEHOLD PURPOSES, ONLY FOR BUSINESSES AND PROFESSIONAL USERS. YOU MUST NOT ACCESS OR USE OUR SERVICES, UNLESS (A) YOU ARE ACTING IN A BUSINESS OR PROFESSIONAL CAPACITY, (B) YOU ACCEPT THE SocialAD TERMS ON BEHALF OF YOURSELF AND, IF APPLICABLE, YOUR ORGANIZATION, AND (C) IF YOU ARE ACTING ON BEHALF OF YOUR ORGANIZATION, YOU ARE AUTHORIZED TO DO SO. IF YOU ACCESS OR USE ANY OF OUR SERVICES, THE SocialAD TERMS FORM A LEGALLY BINDING CONTRACT BETWEEN YOU AND, IF APPLICABLE, YOUR ORGANIZATION (COLLECTIVELY REFERRED TO AS &#8220;YOU&#8221; HEREINAFTER) AND SocialAD.<br />
<span style="text-decoration: underline;">ARBITRATION NOTICE AND CLASS ACTION WAIVER</span>: EXCEPT FOR CERTAIN TYPES OF DISPUTES DESCRIBED IN SECTION 12 BELOW OR WHERE PROHIBITED BY APPLICABLE LAW, YOU AGREE THAT DISPUTES BETWEEN YOU AND SocialAD WILL BE RESOLVED BY BINDING, INDIVIDUAL ARBITRATION AND YOU WAIVE YOUR RIGHT TO PARTICIPATE IN A CLASS ACTION LAWSUIT OR CLASS-WIDE ARBITRATION</p>
<h2>1. Your Rights and Obligations</h2>
<p>1.1 <span style="text-decoration: underline;">Access to Services</span>.  We grant you a non-exclusive, non-transferable, revocable, limited, personal right to access our Services. We do not authorize other use or access, including, without limitation, by robots, spiders, crawlers and scraping technologies. You are responsible for setting your own username and password (“<strong>Login Information</strong>”) and should not allow any third party to access or use your Login Information. You are responsible for all individuals that access the Services through your Login Information (“<strong>Authorized Users</strong>”). You and your Authorized Users may use the Services only for your own business, not to access the Services in order to build a similar or competitive product or service or copy any ideas, features, functions, or graphics of the Services.</p>
<p>1.2 <span style="text-decoration: underline;">Facebook or Instagram Account.</span> We provide you with a technical application which allows you to publish and manage ads on <a href="http://www.facebook.com">www.facebook.com</a> (“<strong>Facebook</strong>”) and <a href="http://www.instagram.com">www.instagram.com</a> (“<strong>Instagram</strong>”). Therefore, in order to use our Services, you must be a registered Facebook or Instagram user and have an advertising account with Facebook or Instagram.</p>
<p>1.3 <span style="text-decoration: underline;">Ads Content</span>. You are solely responsible for all Ads Content that you or your Authorized Users upload, publish, display, link to, or otherwise make available via the Services. We have the right but no obligation to review, filter, block, or remove any Ads Content that you publish or make available via our Services. UNDER NO CIRCUMSTANCES WILL WE BE LIABLE IN ANY WAY FOR ADS CONTENT POSTED ON OR MADE AVAILABLE THROUGH OUR SERVICES BY YOU OR ANY OTHER THIRD PARTY. “<strong>Ads Content</strong>” includes all information, text, images, photos, videos, audio, documents and other content in any media and format which is provided or made available to us in connection with your use of the Services.</p>
<h2>2. Third Party Content and Services</h2>
<p>2.1 We are not responsible for any services provided by Facebook, Instagram (the “<strong>Social Platforms</strong>”), or for any other services, information or content accessed or purchased through SocialAD, which you may be able to access, use or connect to with our Services (together, the &#8220;<strong>Third-Party Services</strong>&#8220;). If you access a Third-Party Service through us, you do so at your own risk. When accessing Facebook or Instagram services, you are responsible to comply with all of their terms, conditions, policies and guidelines which they may impose on their users including those published at <a href="https://www.facebook.com/terms.php">https://www.facebook.com/terms.php</a>, and <a href="https://www.facebook.com/policies/ads/">https://www.facebook.com/policies/ads/</a> (the “<strong>Third-Party Terms</strong>”).  You remain responsible for the payment of the ads purchased through our Services directly to the Social Platforms.</p>
<p>2.2 You understand that we have the right but no obligation to preview, verify, flag, modify Ads Content and that you must bear all risks associated with the publishing of ads on the Social Platforms. You also agree that Services interoperate with Social Platforms, and that our Services are highly dependent on the availability of the Social Platforms.  If at any time the Social Platforms cease to make their features or programs available to us on reasonable terms, we may cease to provide access to such features or programs to you. We assume no responsibility or liability related to Ad Content or to any Ad Content not being transferred to or published on the Social Platforms as a result of a malfunction in our Services.</p>
<h2>3. Confidentiality and Data Protection</h2>
<p>3.1 <span style="text-decoration: underline;">Confidentiality</span>.  If we share non-public information about our Services, you must keep it confidential and use reasonable security measures to prevent disclosure or access by unauthorized persons.</p>
<p>3.2 <span style="text-decoration: underline;">Personal Data</span>.  We will not use or control any of the personal data that you process with our Services, we merely offer you tools with which you can process data. You must comply with all applicable data privacy and data protection laws. </p>
<h2>4. Intellectual Property</h2>
<p>4.1 <span style="text-decoration: underline;">Ads Content.</span> You retain all right, title and interest to your Ads Content which you may upload to or with our Services. We will not use your Ads Content except for purposes of providing, supporting and improving our Services and in full compliance with all SocialAD Terms.</p>
<p>4.2 <span style="text-decoration: underline;">Feedback</span>. You may from time to time provide suggestions, comments or other feedback to SocialAD with respect to the Services (“<strong>Feedback</strong>”). Feedback, even if designated as confidential by you, shall not create any confidentiality obligation for us. Notwithstanding the foregoing, we will not disclose to any third party that you are the source of any Feedback. You shall, and hereby do, grant to us a non-exclusive, worldwide, perpetual, irrevocable, transferable, sublicensable, royalty-free, fully paid-up license to use and exploit the Feedback for any purpose.</p>
<p>4.3 <span style="text-decoration: underline;">Services.</span> We retain all right, title, and interest in and to the Services.</p>
<h2>5. Cancellation</h2>
<p>The SocialAD Terms shall remain in effect until either of us terminate them in accordance with this Section 7.</p>
<p>5.1 <span style="text-decoration: underline;">Cancellation of Services.</span>  You can cancel your Services at any time by following the cancellation procedure published <a href="https://SocialAD.zendesk.com/hc/en-us/articles/216071738-How-to-unsubscribe-from-SocialAD">here</a>. If you cancel paid Services, you must pay throughout any agreed term and you are not entitled to any refunds.</p>
<p>5.2 <span style="text-decoration: underline;">Cancellation by SocialAD</span>. We may also cancel your Services, at our sole discretion, for any reason, without notice at any time. If you prepaid for Services for a specified term, and we terminate your Services under this section, we shall offer a pro rata refund of the prepaid fees.</p>
<p>5.3 <span style="text-decoration: underline;">Termination for Cause</span>. We may both terminate the SocialAD Terms, effective immediately, if the other party commits a material breach of the SocialAD Terms and fails to remedy such breach within thirty (30) days of receiving a written request to cure. </p>
<p>5.4 <span style="text-decoration: underline;">Effects of Termination.</span> Upon cancellation or termination of the Services by either party for any reason: (i) we will cease providing you Services and you will no longer be able to access your account; (ii) unless otherwise provided in these SocialAD Terms, you will not be entitled to any refunds, and you shall pay us all unpaid amounts owing. All provisions of the SocialAD Terms that by their nature are intended to survive, including but not limited to any disclaimer of warranty and limitation of liability provisions, shall survive the termination or expiry of the SocialAD Terms.</p>
<h2>6. Warranty Disclaimer</h2>
<p>6.1 <span style="text-decoration: underline;">No Express Warranties.</span>  WE OFFER THE SERVICES &#8220;AS IS,&#8221; WITHOUT ANY EXPRESS WARRANTIES, REPRESENTATIONS, GUARANTEES OR CONDITIONS, UNLESS WE EXPRESSLY AGREE TO A LIMITED WARRANTY WITH A SPECIFIC REFERENCE TO THIS SECTION 8.1.</p>
<p>6.2 <span style="text-decoration: underline;">Disclaimers.</span>  YOU USE ALL SERVICES AT YOUR OWN RISK. TO THE GREATEST EXTENT PERMITTED BY APPLICABLE LAW, WE DISCLAIM ANY WARRANTIES, REPRESENTATIONS, GUARANTEES AND CONDITIONS OF ANY KIND, WHETHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE. WITHOUT LIMITING THE GENERALITY OF THE FOREGOING, WE SPECIFICALLY DISCLAIM ALL EXPRESS OR IMPLIED WARRANTIES OF DESIGN, MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, QUALITY, AND NONINFRINGEMENT, THAT THE SERVICES WILL MEET YOUR REQUIREMENTS, OR THAT OUR SERVICES WILL ALWAYS BE AVAILABLE, ACCESSIBLE, UNINTERRUPTED, TIMELY, SECURE, ACCURATE, COMPLETE, OR ERROR-FREE. IN ADDITION, WE DISCLAIM ANY RESPONSIBILITY FOR ANY THIRD-PARTY SERVICES (INCLUDING FACEBOOK OR INSTAGRAM) OR ACTIVITIES, ANY CONNECTION TO OR TRANSMISSION FROM THE INTERNET, OR SOCIAL PLATFORMS, ANY HACKING, TAMPERING, OR OTHER UNAUTHORIZED ACCESS OR USE OF THE SERVICES OR YOUR ACCOUNT OR THE INFORMATION CONTAINED THEREIN (INCLUDING ADS CONTENT). NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED FROM US OR ELSEWHERE WILL CREATE ANY WARRANTY OR CONDITION NOT EXPRESSLY STATED IN THESE SocialAD TERMS. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING THE FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY PROVIDED HEREIN.</p>
<h2>7. Sole Remedy</h2>
<p>IF YOU ARE DISSATISFIED WITH OUR SERVICES OR HARMED BY US OR BY ANYTHING RELATED TO OUR SERVICES, YOU MAY TERMINATE THE SocialAD TERMS IN ACCORDANCE WITH SECTION 7.3, AS APPLICABLE. SUCH TERMINATION SHALL BE YOUR SOLE AND EXCLUSIVE REMEDY (AND OUR SOLE AND EXCLUSIVE LIABILITY) FOR ANY BREACH OF CONTRACT.</p>
<h2>8. Indemnification</h2>
<p>You shall defend, indemnify, and hold harmless SocialAD, and our affiliates, directors, officers, employees, and agents from and against all claims, losses, damages, penalties, liability, and costs, including reasonable attorneys’ fees, of any kind or nature that are in connection with or arising out of a claim (a) alleging that your Ads Content infringes or violates the intellectual property rights, privacy rights, or other rights of a third party or violates any applicable law; (b) relating to, or arising from, Ads Content or your breach of any SocialAD Terms or (c) relating to, or arising from, your use of any Third-Party Services (including your breach of the Third-Party Terms).</p>


				</div>
            </div>
        </div>
    </div>
</div>
@endsection